branch-defaults:
  master:
    environment: prod
    group_suffix: null
global:
  application_name: gymbox-bot
  branch: null
  default_ec2_keyname: default-ec2
  default_platform: Docker 18.06.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
